#Stage 1: build

FROM node:22 AS build

# Update package lists and upgrade installed packages

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/* 

# Set the working directory

WORKDIR /app

# Copy the package files

COPY package*.json .

# Install the dependencies

RUN npm ci

# Copy the rest code

COPY . . 

# Building the Frontend

RUN npm run build 

# Stage2: Runtime

FROM  nginx:1.29-alpine

# Updates Alpine's package index
RUN apk update

# Set the working directory

WORKDIR /app

# Copy the package files

COPY --from=build /app/build /usr/share/nginx/html

# Copy Nginx configuration
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
